spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: test
  main:
    banner-mode: "off"

logging:
  level:
    root: WARN
    com.example: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  main:
    banner-mode: "off"

logging:
  level:
    root: INFO
    com.example: INFO